os: linux
dist: bionic
language: node_js
node_js:
    - 14

addons:
    - chrome: stable
    - firefox: "latest"

services:
    - xvfb

before_script:
    - git clone https://github.com/wikimedia/mediawiki.git --branch REL1_34 --single-branch --depth 1 mediawiki-src
    - ls -la
    - node getlanguages.js mediawiki-src

script:
    - npm run node-test
    - npm run browsers-test
